services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse

  generator:
    build: ./generator
    depends_on:
      - redis

  collector:
    build: ./collector
    depends_on:
      - redis
      - clickhouse